version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          command: cat publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: int128/helm-charts
      - run:
          name: Verify
          command: |
            alias helm=/tmp/helm/bin/linux-amd64/helm
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              helm repo add int128 https://int128.github.io/helm-charts
              helm repo update
              helm repo list
              helm inspect int128/example
            fi
